import { Department, Staff } from "./types";

export const department: Department[] = [
  {
    name: "Emergency",
    workdays: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    time: ["6:00am - 4:00pm", "4:00pm - 10:00pm", "10:00pm - 6:00am"],
  },
  {
    name: "Pediatrics",
    workdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    time: ["6:00am - 4:00pm"],
  },
  {
    name: "Surgery",
    workdays: ["Monday", "Thursday"],
    time: ["6:00am - 4:00pm", "10:00pm - 6:00am"],
  },
  {
    name: "Maternity",
    workdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    time: ["6:00am - 4:00pm", "4:00pm - 10:00pm", "10:00pm - 6:00am"],
  },
  {
    name: "Radiology",
    workdays: ["Monday", "Wednesday", "Friday"],
    time: ["6:00am - 4:00pm"],
  },
];

export const validAdminIds = ["admin007", "admin026"];
export const validStaffIds = [
  "staff11",
  "staff4",
  "doc001",
  "nur002",
  "doc002",
  "nur003",
];

export const staff: Staff[] = [
  
  { id: "emerdoc001", name: "Dr. AbdulQudus", role: "doctor", department: "Emergency" },
  { id: "emerdoc002", name: "Dr. Adebukola", role: "doctor", department: "Emergency" },
  { id: "emerdoc003", name: "Dr. Akinwumi", role: "doctor", department: "Emergency" },
  { id: "emerdoc004", name: "Dr. Oyewale", role: "doctor", department: "Emergency" },
  { id: "emerdoc005", name: "Dr. Ubaydah", role: "doctor", department: "Emergency" },
  { id: "emerdoc006", name: "Dr. Bukunmi", role: "doctor", department: "Emergency" },
  { id: "emerdoc007", name: "Dr. Emmanuel", role: "doctor", department: "Emergency" },
  { id: "emerdoc008", name: "Dr. Banjo", role: "doctor", department: "Emergency" },
  { id: "emernur001", name: "Nurse Amao", role: "nurse", department: "Emergency" },
  { id: "emernur002", name: "Nurse Tayo", role: "nurse", department: "Emergency" },
  { id: "emernur003", name: "Nurse Ayomide", role: "nurse", department: "Emergency" },
  { id: "emernur004", name: "Nurse Oyetunji", role: "nurse", department: "Emergency" },
  { id: "emernur005", name: "Nurse Durosinmi", role: "nurse", department: "Emergency" },
  { id: "emernur006", name: "Nurse Raji", role: "nurse", department: "Emergency" },
  { id: "emernur007", name: "Nurse Damilare", role: "nurse", department: "Emergency" },
  { id: "emernur008", name: "Nurse Habibat", role: "nurse", department: "Emergency" },
  
{ id: "emerdoc009", name: "Dr. Kehinde", role: "doctor", department: "Emergency" },
{ id: "emerdoc010", name: "Dr. Zainab", role: "doctor", department: "Emergency" },
{ id: "emerdoc011", name: "Dr. Rasaq", role: "doctor", department: "Emergency" },
{ id: "emerdoc012", name: "Dr. Jimoh", role: "doctor", department: "Emergency" },
{ id: "emerdoc013", name: "Dr. Ibrahim", role: "doctor", department: "Emergency" },
{ id: "emerdoc014", name: "Dr. Salim", role: "doctor", department: "Emergency" },
{ id: "emerdoc015", name: "Dr. Taiwo", role: "doctor", department: "Emergency" },
{ id: "emerdoc016", name: "Dr. Sofiat", role: "doctor", department: "Emergency" },
{ id: "emernur009", name: "Nurse Zulaihat", role: "nurse", department: "Emergency" },
{ id: "emernur010", name: "Nurse Kafayat", role: "nurse", department: "Emergency" },
{ id: "emernur011", name: "Nurse Taofeek", role: "nurse", department: "Emergency" },
{ id: "emernur012", name: "Nurse Sadiq", role: "nurse", department: "Emergency" },
{ id: "emernur013", name: "Nurse Yetunde", role: "nurse", department: "Emergency" },
{ id: "emernur014", name: "Nurse Rukayat", role: "nurse", department: "Emergency" },
{ id: "emernur015", name: "Nurse Lateef", role: "nurse", department: "Emergency" },
{ id: "emernur016", name: "Nurse Abimbola", role: "nurse", department: "Emergency" },

{ id: "pedidoc009", name: "Dr. Anike", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc010", name: "Dr. Sulaimon", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc011", name: "Dr. Morenike", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc012", name: "Dr. Owolabi", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc013", name: "Dr. Hamza", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc014", name: "Dr. Yetunde", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc015", name: "Dr. Azeez", role: "doctor", department: "Pediatrics" },
{ id: "pedidoc016", name: "Dr. Roseline", role: "doctor", department: "Pediatrics" },
{ id: "pedinur009", name: "Nurse Maryam", role: "nurse", department: "Pediatrics" },
{ id: "pedinur010", name: "Nurse Azeezat", role: "nurse", department: "Pediatrics" },
{ id: "pedinur011", name: "Nurse Abass", role: "nurse", department: "Pediatrics" },
{ id: "pedinur012", name: "Nurse Lawal", role: "nurse", department: "Pediatrics" },
{ id: "pedinur013", name: "Nurse Sulaimon", role: "nurse", department: "Pediatrics" },
{ id: "pedinur014", name: "Nurse Anu", role: "nurse", department: "Pediatrics" },
{ id: "pedinur015", name: "Nurse Lukman", role: "nurse", department: "Pediatrics" },
{ id: "pedinur016", name: "Nurse Halimah", role: "nurse", department: "Pediatrics" },

  // Pediatrics
  { id: "pedidoc001", name: "Dr. Aminat", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc002", name: "Dr. Barakat", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc003", name: "Dr. Hakimat", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc004", name: "Dr. Kamal", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc005", name: "Dr. Abdullateef", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc006", name: "Dr. Adeoye", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc007", name: "Dr. Furher", role: "doctor", department: "Pediatrics" },
  { id: "pedidoc008", name: "Dr. Sarafudeen", role: "doctor", department: "Pediatrics" },
  { id: "pedinur001", name: "Nurse Rahmat", role: "nurse", department: "Pediatrics" },
  { id: "pedinur002", name: "Nurse Kudirat", role: "nurse", department: "Pediatrics" },
  { id: "pedinur003", name: "Nurse Omar", role: "nurse", department: "Pediatrics" },
  { id: "pedinur004", name: "Nurse Ridwan", role: "nurse", department: "Pediatrics" },
  { id: "pedinur005", name: "Nurse Akinbola", role: "nurse", department: "Pediatrics" },
  { id: "pedinur006", name: "Nurse Sukurat", role: "nurse", department: "Pediatrics" },
  { id: "pedinur007", name: "Nurse Mubarak", role: "nurse", department: "Pediatrics" },
  { id: "pedinur008", name: "Nurse Titi", role: "nurse", department: "Pediatrics" },
  

  // Surgery
  { id: "surgdoc001", name: "Dr. Banjo", role: "doctor", department: "Surgery" },
  { id: "surgdoc002", name: "Dr. Temitope", role: "doctor", department: "Surgery" },
  { id: "surgdoc003", name: "Dr. Akande", role: "doctor", department: "Surgery" },
  { id: "surgdoc004", name: "Dr. Aisha", role: "doctor", department: "Surgery" },
  { id: "surgdoc005", name: "Dr. Adunni", role: "doctor", department: "Surgery" },
  { id: "surgdoc006", name: "Dr. Khadijah", role: "doctor", department: "Surgery" },
  { id: "surgdoc007", name: "Dr. Oyewale", role: "doctor", department: "Surgery" },
  { id: "surgdoc008", name: "Dr. Tola", role: "doctor", department: "Surgery" },
  { id: "surgnur001", name: "Nurse Funmi", role: "nurse", department: "Surgery" },
  { id: "surgnur002", name: "Nurse Wale", role: "nurse", department: "Surgery" },
  { id: "surgnur003", name: "Nurse Nasirat", role: "nurse", department: "Surgery" },
  { id: "surgnur004", name: "Nurse Grace", role: "nurse", department: "Surgery" },
  { id: "surgnur005", name: "Nurse Olaoye", role: "nurse", department: "Surgery" },
  { id: "surgnur006", name: "Nurse Gretta", role: "nurse", department: "Surgery" },
  { id: "surgnur007", name: "Nurse Tunde", role: "nurse", department: "Surgery" },
  { id: "surgnur008", name: "Nurse Stella", role: "nurse", department: "Surgery" },
  { id: "surgdoc009", name: "Dr. Tosin", role: "doctor", department: "Surgery" },
{ id: "surgdoc010", name: "Dr. Farooq", role: "doctor", department: "Surgery" },
{ id: "surgdoc011", name: "Dr. Adeniyi", role: "doctor", department: "Surgery" },
{ id: "surgdoc012", name: "Dr. Fadilah", role: "doctor", department: "Surgery" },
{ id: "surgdoc013", name: "Dr. Muinat", role: "doctor", department: "Surgery" },
{ id: "surgdoc014", name: "Dr. Kunle", role: "doctor", department: "Surgery" },
{ id: "surgdoc015", name: "Dr. Lukman", role: "doctor", department: "Surgery" },
{ id: "surgdoc016", name: "Dr. Balikis", role: "doctor", department: "Surgery" },
{ id: "surgnur009", name: "Nurse Kareem", role: "nurse", department: "Surgery" },
{ id: "surgnur010", name: "Nurse Mary", role: "nurse", department: "Surgery" },
{ id: "surgnur011", name: "Nurse Quadri", role: "nurse", department: "Surgery" },
{ id: "surgnur012", name: "Nurse Ganiyat", role: "nurse", department: "Surgery" },
{ id: "surgnur013", name: "Nurse Abisola", role: "nurse", department: "Surgery" },
{ id: "surgnur014", name: "Nurse Sodiq", role: "nurse", department: "Surgery" },
{ id: "surgnur015", name: "Nurse Modupe", role: "nurse", department: "Surgery" },
{ id: "surgnur016", name: "Nurse Tosin", role: "nurse", department: "Surgery" },

  // Maternity
  { id: "matedoc001", name: "Dr. Hassan", role: "doctor", department: "Maternity" },
  { id: "matedoc002", name: "Dr. Hussein", role: "doctor", department: "Maternity" },
  { id: "matedoc003", name: "Dr. Abdulquadri", role: "doctor", department: "Maternity" },
  { id: "matedoc004", name: "Dr. Abiodun", role: "doctor", department: "Maternity" },
  { id: "matedoc005", name: "Dr. Habeeb", role: "doctor", department: "Maternity" },
  { id: "matedoc006", name: "Dr. Shuhaib", role: "doctor", department: "Maternity" },
  { id: "matedoc007", name: "Dr. Olawale", role: "doctor", department: "Maternity" },
  { id: "matedoc008", name: "Dr. Mark", role: "doctor", department: "Maternity" },
  { id: "matenur001", name: "Nurse Yewande", role: "nurse", department: "Maternity" },
  { id: "matenur002", name: "Nurse Diallo", role: "nurse", department: "Maternity" },
  { id: "matenur003", name: "Nurse Blessing", role: "nurse", department: "Maternity" },
  { id: "matenur004", name: "Nurse Seun", role: "nurse", department: "Maternity" },
  { id: "matenur005", name: "Nurse Fawaz", role: "nurse", department: "Maternity" },
  { id: "matenur006", name: "Nurse Dawud", role: "nurse", department: "Maternity" },
  { id: "matenur007", name: "Nurse Bose", role: "nurse", department: "Maternity" },
  { id: "matenur008", name: "Nurse Usman", role: "nurse", department: "Maternity" },
  { id: "matedoc009", name: "Dr. Zubair", role: "doctor", department: "Maternity" },
{ id: "matedoc010", name: "Dr. Opeyemi", role: "doctor", department: "Maternity" },
{ id: "matedoc011", name: "Dr. Sofiyyah", role: "doctor", department: "Maternity" },
{ id: "matedoc012", name: "Dr. Akinlabi", role: "doctor", department: "Maternity" },
{ id: "matedoc013", name: "Dr. Busayo", role: "doctor", department: "Maternity" },
{ id: "matedoc014", name: "Dr. Faith", role: "doctor", department: "Maternity" },
{ id: "matedoc015", name: "Dr. Fisayo", role: "doctor", department: "Maternity" },
{ id: "matedoc016", name: "Dr. Okiki", role: "doctor", department: "Maternity" },
{ id: "matenur009", name: "Nurse Peace", role: "nurse", department: "Maternity" },
{ id: "matenur010", name: "Nurse Zainab", role: "nurse", department: "Maternity" },
{ id: "matenur011", name: "Nurse Ibrahim", role: "nurse", department: "Maternity" },
{ id: "matenur012", name: "Nurse Rofiat", role: "nurse", department: "Maternity" },
{ id: "matenur013", name: "Nurse Monsurat", role: "nurse", department: "Maternity" },
{ id: "matenur014", name: "Nurse Kehinde", role: "nurse", department: "Maternity" },
{ id: "matenur015", name: "Nurse Toyin", role: "nurse", department: "Maternity" },
{ id: "matenur016", name: "Nurse Sulaimon", role: "nurse", department: "Maternity" },

  // Radiology
  { id: "radidoc001", name: "Dr. Ife", role: "doctor", department: "Radiology" },
  { id: "radidoc002", name: "Nurse Tope", role: "doctor", department: "Radiology" },
  { id: "radidoc003", name: "Dr. Chika", role: "doctor", department: "Radiology" },
  { id: "radidoc004", name: "Dr. Bola", role: "doctor", department: "Radiology" },
  { id: "radidoc005", name: "Dr. Kudus", role: "doctor", department: "Radiology" },
  { id: "radidoc006", name: "Nurse TemiTope", role: "doctor", department: "Radiology" },
  { id: "radidoc007", name: "Dr. Chinedu", role: "doctor", department: "Radiology" },
  { id: "radidoc008", name: "Dr. Wale", role: "doctor", department: "Radiology" },
  { id: "radinur001", name: "Nurse Islammiyah", role: "nurse", department: "Radiology" },
  { id: "radinur002", name: "Nurse Anthony", role: "nurse", department: "Radiology" },
  { id: "radinur003", name: "Nurse Umar", role: "nurse", department: "Radiology" },
  { id: "radinur004", name: "Nurse Muiz", role: "nurse", department: "Radiology" },
  { id: "radinur005", name: "Nurse Israel", role: "nurse", department: "Radiology" },
  { id: "radinur006", name: "Nurse Ishaq", role: "nurse", department: "Radiology" },
  { id: "radinur007", name: "Nurse Ibrahim", role: "nurse", department: "Radiology" },
  { id: "radinur008", name: "Nurse Abdullahi", role: "nurse", department: "Radiology" },
  { id: "radidoc009", name: "Dr. Sherifat", role: "doctor", department: "Radiology" },
{ id: "radidoc010", name: "Dr. Yusuff", role: "doctor", department: "Radiology" },
{ id: "radidoc011", name: "Dr. Ganiyat", role: "doctor", department: "Radiology" },
{ id: "radidoc012", name: "Dr. Suleiman", role: "doctor", department: "Radiology" },
{ id: "radidoc013", name: "Dr. Mujeeb", role: "doctor", department: "Radiology" },
{ id: "radidoc014", name: "Dr. Tawa", role: "doctor", department: "Radiology" },
{ id: "radidoc015", name: "Dr. Dada", role: "doctor", department: "Radiology" },
{ id: "radidoc016", name: "Dr. Sheriff", role: "doctor", department: "Radiology" },
{ id: "radinur009", name: "Nurse Mercy", role: "nurse", department: "Radiology" },
{ id: "radinur010", name: "Nurse Femi", role: "nurse", department: "Radiology" },
{ id: "radinur011", name: "Nurse Salam", role: "nurse", department: "Radiology" },
{ id: "radinur012", name: "Nurse Halima", role: "nurse", department: "Radiology" },
{ id: "radinur013", name: "Nurse Abdulahi", role: "nurse", department: "Radiology" },
{ id: "radinur014", name: "Nurse Afeez", role: "nurse", department: "Radiology" },
{ id: "radinur015", name: "Nurse Basit", role: "nurse", department: "Radiology" },
{ id: "radinur016", name: "Nurse Mariam", role: "nurse", department: "Radiology" },
];
